version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo 'hello world'
      - echo 'this is version 1'
      - echo '${$PROJECT,,}'
      #- aws codepipeline start-pipeline-execution --name $PROJECT-frontend-$STAGE-pipeline
  post_build:
    commands:
      - echo 'post build phases executed successfully'
artifacts:
  files: 
    - '**/*'
