version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo 'hello world'
      - aws s3 ls
  post_build:
    commands:
      - echo 'post build phases executed successfully'
artifacts:
  files: 
    - '**/*'
